# Generated by Django 5.0.3 on 2026-01-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajecontacto',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
