# Generated by Django 5.2.7 on 2025-12-24 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='camara.category'),
        ),
    ]
