# Generated by Django 5.0.3 on 2026-01-03 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0005_alter_category_options_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together={('category', 'nombre')},
        ),
    ]
