# Generated by Django 5.0.3 on 2026-01-03 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camara', '0006_alter_producto_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='producto',
            unique_together=set(),
        ),
    ]
